.TH kickstart
.SH NAME
.B kickstart \-
setup a new kickstart project.

.SH SYNOPSIS
.B yo kickstart
[\fB\-\-skip-\install\fR]

.SH DESCRIPTION
.B yo kickstart
Starts the Yeoman generator Kickstart and guides you through the process of setting up a new project.

.SH OPTIONS
.TP
.BR \-\-skip\-install
Skip installation of bower packages, node packages and gems at the end of the setup process.
