.TH removecomponent
.SH NAME
.B removecomponent \-
removes a component from the project.

.SH SYNOPSIS
.B yo kickstart:removecomponent
.IR name

.SH DESCRIPTION
.B removecomponent
Removes JS, QUnit, SCSS or HTML from components/app and removes references from requireJS config file and main SCSS file.
